import { AppSidebar } from '@/components/layout/sidebar'
import { Button } from '@/components/ui/button'
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet'
import { SidebarProvider } from '@/components/ui/sidebar'
import { Menu } from 'lucide-react'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Test App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="grid min-h-screen w-full">
					<SidebarProvider>
						<div className="hidden border-r bg-muted/40 md:block">
							<AppSidebar />
						</div>
						<div className="flex-1 w-full bg-gray-100/40 dark:bg-gray-800/40">
							<main className=" flex-1 w-full flex-col gap-4 p-4 lg:gap-6 lg:p-6">
								{children}
							</main>
						</div>
					</SidebarProvider>
				</div>
			</body>
		</html>
	)
}
