import { AppSidebar } from '@/components/layout/sidebar'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Test App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="bg-background relative z-10 flex min-h-svh flex-col">
					<SidebarProvider>
						<AppSidebar></AppSidebar>
						<main className="bg-neutral-200 w-full">
							<SidebarTrigger />
							{children}
						</main>
					</SidebarProvider>
				</div>
			</body>
		</html>
	)
}
